jdk:
  - oraclejdk8

language: scala

scala:
  - 2.12.7

install:
  - true

branches:
  only:
    - master
    
script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
